apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: backend
    spec:
      containers:
        - env:
            - name: PGCONNECTIONSTRING
              valueFrom:
                configMapKeyRef:
                  key: PGCONNECTIONSTRING
                  name: docker-env
            - name: PGDATABASE
              valueFrom:
                configMapKeyRef:
                  key: PGDATABASE
                  name: docker-env
            - name: PGHOST
              valueFrom:
                configMapKeyRef:
                  key: PGHOST
                  name: docker-env
            - name: PGPASSWORD
              valueFrom:
                configMapKeyRef:
                  key: PGPASSWORD
                  name: docker-env
            - name: PGPORT
              valueFrom:
                configMapKeyRef:
                  key: PGPORT
                  name: docker-env
            - name: PGUSER
              valueFrom:
                configMapKeyRef:
                  key: PGUSER
                  name: docker-env
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  key: PORT
                  name: docker-env
            - name: SECRET_JWT_SEED
              valueFrom:
                configMapKeyRef:
                  key: SECRET_JWT_SEED
                  name: docker-env
          image: alfonsomelgar/backend:latest
          name: backend
          ports:
            - containerPort: 4000
          resources: {}
      restartPolicy: Always
status: {}
